services:
  ms_sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123!"
      MSSQL_PID: "Developer"
    volumes:
      - db_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
        
  sqlserver.configurator:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - ms_sql_server
    entrypoint: /bin/bash
    #command: -c "sleep 10 && /opt/mssql-tools/bin/sqlcmd -S ms_sql_server -U sa -P Password123! -i /scripts/init-db.sql"
    volumes:
      - /usr/src/app/:/scripts # Refer to copy command in Dockerfile
volumes:
  db_data:
